CREATE TABLE [Tbl_Player] ( [Pl_Id] INT IDENTITY (1,1) PRIMARY KEY, [Pl_Namn] NVARCHAR (100) NOT NULL, [Pl_Färg] NVARCHAR (10) NOT NULL, CONSTRAINT CK_Player_Färg CHECK (Pl_Färg IN ('Röd', 'Blå', 'Grön','Gul')) ); 

CREATE TABLE [Tbl_Game] ( [Ga_Id] INT IDENTITY (1,1) PRIMARY KEY, [Pl1_Id] INT NOT NULL, [Pl2_Id] INT NOT NULL, [Ga_StartTime] DATETIME NOT NULL, [Ga_EndTime] DATETIME NULL, [Vinnare_Id] INT NULL CONSTRAINT FK_GAME_PLAYER1 FOREIGN KEY (Pl1_Id) REFERENCES Tbl_Player (Pl_Id), CONSTRAINT FK_GAME_PLAYER2 FOREIGN KEY (Pl2_Id) REFERENCES Tbl_Player (Pl_Id), CONSTRAINT FK_Game_Winner FOREIGN KEY (Vinnare_Id) REFERENCES Tbl_Player(Pl_Id) ); 

CREATE TABLE [Tbl_Move] ( [Mo_Move] INT PRIMARY KEY, [Pl_Id] INT NOT NULL, [Ga_Id] INT NOT NULL, [Mo_Column] INT NOT NULL, [Mo_Rad] INT NOT NULL, [Mo_Time] DATETIME NOT NULL, CONSTRAINT FK_Move_Player FOREIGN KEY (Pl_Id) REFERENCES Tbl_Player(Pl_Id), CONSTRAINT FK_Move_Game FOREIGN KEY (Ga_Id) REFERENCES Tbl_Game (Ga_Id) ); 

CREATE TABLE [Tbl_Highscore] ( [Hi_Id] INT IDENTITY (1,1) PRIMARY KEY, [Pl_Id] INT NOT NULL, [Ga_Id] INT NOT NULL, [Hi_Poäng] INT NOT NULL, CONSTRAINT FK_Highscore_Player FOREIGN KEY (Pl_Id) REFERENCES Tbl_Player (Pl_Id), CONSTRAINT FK_Highscore_Game FOREIGN KEY (Ga_Id) REFERENCES Tbl_Game (Ga_Id) 

); 